# These are supported funding model platforms

github: hernanmd
# patreon: 
open_collective: hernanmd
ko_fi: hernanmd
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: hernan
issuehunt: hernanmd
# lfx_crowdfunding: 
buy_me_a_coffee: hernanmd
